import { Recipe } from "@/types/recipe";

export const PLACEHOLDER_RECIPES: Recipe[] = [
  {
    id: "1",
    title: "Chicken Parmesan",
    description:
      "A popular Italian dish featuring juicy chicken with a crisp, perfectly seasoned crust topped with marinara and melty cheese.",
    imageUrl:
      "https://images.unsplash.com/photo-1638525136591-ab94ebe13afe?w=800",
    cuisine: "Italian",
    cookTimeMinutes: 60,
    baseServings: 4,
    tags: ["chicken", "italian", "cheese"],
    instructions: [
      "Preheat the oven to 450 degrees F.",
      "Beat eggs in a shallow bowl and set aside.",
      "Dip each chicken breast in the beaten eggs then dip in the bread crumbs, pressing crumbs into both sides.",
      "Fry the breaded chicken in a pan with oil until golden.",
      "Transfer chicken to a baking dish.",
      "Top each breast with 2 tablespoons tomato sauce, mozzarella cheese, and fresh basil.",
      "Bake in the preheated oven until cheese is browned and bubbly, 15 to 20 minutes.",
      "Serve and enjoy!",
    ],
    ingredients: [
      { id: "1-1", name: "Chicken breast", quantity: 700, unit: "g" },
      { id: "1-2", name: "Eggs", quantity: 2, unit: "" },
      { id: "1-3", name: "Bread crumbs", quantity: 1, unit: "cup" },
      { id: "1-4", name: "Oil", quantity: 0.5, unit: "cup" },
      { id: "1-5", name: "Tomato sauce", quantity: 0.5, unit: "cup" },
      { id: "1-6", name: "Mozzarella cheese", quantity: 0.5, unit: "cup" },
      { id: "1-7", name: "Basil", quantity: 0.25, unit: "cup" },
    ],
  },
  {
    id: "2",
    title: "Chana Masala",
    description:
      "This Indian chickpea curry features a hearty mixture of chickpeas, tomatoes, onion, green chili, and warm Indian spices.",
    imageUrl:
      "https://images.unsplash.com/photo-1736680056470-948527554276?w=800",
    cuisine: "Indian",
    cookTimeMinutes: 30,
    baseServings: 4,
    tags: ["vegetarian", "indian", "curry"],
    instructions: [
      "Grind onion, tomatoes, garlic, and chili pepper together in a food processor into a paste.",
      "Heat oil in a large skillet over medium heat.",
      "Pour the paste into the skillet and cook until the oil begins to separate from the mixture and is golden brown in color, 2 to 3 minutes.",
      "Season the mixture with chili powder, coriander, garam masala, and turmeric; cook and stir until very hot, 2 to 3 minutes.",
      "Stir water into the mixture to get a thick sauce; bring to a boil and stir chickpeas into the sauce.",
      "Reduce heat to medium and cook until the chickpeas are heated through, 5 to 7 minutes.",
      "Serve and enjoy!",
    ],
    ingredients: [
      { id: "2-1", name: "Onion", quantity: 1, unit: "" },
      { id: "2-2", name: "Crushed tomatoes", quantity: 400, unit: "g" },
      { id: "2-3", name: "Garlic", quantity: 20, unit: "g" },
      { id: "2-4", name: "Chili pepper", quantity: 100, unit: "g" },
      { id: "2-5", name: "Oil", quantity: 3, unit: "tbsp" },
      { id: "2-6", name: "Chili powder", quantity: 1, unit: "tsp" },
      { id: "2-7", name: "Coriander powder", quantity: 1, unit: "tsp" },
      { id: "2-8", name: "Garam masala", quantity: 1, unit: "tsp" },
      { id: "2-9", name: "Turmeric powder", quantity: 0.5, unit: "tsp" },
      { id: "2-10", name: "Water", quantity: 0.25, unit: "cup" },
      { id: "2-11", name: "Chickpeas", quantity: 2, unit: "cup" },
    ],
  },
  {
    id: "3",
    title: "Chicken Tortilla Soup",
    description:
      "This comforting chicken tortilla soup with shredded chicken, black beans, and corn is quick to make and full of flavor.",
    imageUrl:
      "https://images.unsplash.com/photo-1646850148817-c3a5e8a35fd9?w=800",
    cuisine: "Mexican",
    cookTimeMinutes: 40,
    baseServings: 8,
    tags: ["soup", "mexican", "chicken"],
    instructions: [
      "Cut chicken breasts into small pieces.",
      "Heat oil in a stockpot over medium heat.",
      "Add cut up chicken into pot and sauté for 2 minutes.",
      "Add onion and sauté until soft, about 5 minutes.",
      "Stir in chili powder.",
      "Stir in crushed tomatoes and chicken broth; bring to a boil.",
      "Reduce heat and simmer for 5 to 10 minutes.",
      "Stir in black beans, corn, and chili peppers; Simmer for 10 minutes.",
      "Ladle soup into individual serving bowls, top with crushed tortilla chips and enjoy!",
    ],
    ingredients: [
      { id: "3-1", name: "Oil", quantity: 3, unit: "tbsp" },
      { id: "3-2", name: "Onion", quantity: 1, unit: "" },
      { id: "3-3", name: "Crushed tomatoes", quantity: 800, unit: "g" },
      { id: "3-4", name: "Chicken broth", quantity: 4, unit: "cup" },
      { id: "3-5", name: "Chili powder", quantity: 2, unit: "tsp" },
      { id: "3-6", name: "Black beans", quantity: 2, unit: "cup" },
      { id: "3-7", name: "Chicken breast", quantity: 350, unit: "g" },
      { id: "3-8", name: "Corn", quantity: 1, unit: "cup" },
      { id: "3-9", name: "Chili pepper", quantity: 100, unit: "g" },
      { id: "3-10", name: "Tortilla chips", quantity: 0.5, unit: "cup" },
    ],
  },
  {
    id: "4",
    title: "Beef Tacos",
    description:
      "Juicy seasoned ground beef in crispy taco shells topped with shredded cheese, lettuce, and fresh tomato. A family favorite ready in under 30 minutes.",
    imageUrl:
      "https://images.unsplash.com/photo-1599974579688-8dbdd335c77f?w=800",
    cuisine: "Mexican",
    cookTimeMinutes: 25,
    baseServings: 4,
    tags: ["tacos", "mexican", "beef"],
    instructions: [
      "Heat oil in a skillet over medium-high heat.",
      "Add ground beef and cook, breaking it apart, until browned.",
      "Drain excess fat from the skillet.",
      "Stir in taco seasoning and water, simmer for 5 minutes.",
      "Warm taco shells in the oven according to package instructions.",
      "Fill shells with beef mixture.",
      "Top with shredded cheese, lettuce, and diced tomato.",
      "Serve immediately and enjoy.",
    ],
    ingredients: [
      { id: "4-1", name: "Ground beef", quantity: 500, unit: "g" },
      { id: "4-2", name: "Taco shells", quantity: 12, unit: "" },
      { id: "4-3", name: "Taco seasoning", quantity: 2, unit: "tbsp" },
      { id: "4-4", name: "Water", quantity: 0.5, unit: "cup" },
      { id: "4-5", name: "Shredded cheese", quantity: 1, unit: "cup" },
      { id: "4-6", name: "Lettuce", quantity: 1, unit: "cup" },
      { id: "4-7", name: "Tomato", quantity: 2, unit: "" },
      { id: "4-8", name: "Oil", quantity: 1, unit: "tbsp" },
    ],
  },
  {
    id: "5",
    title: "Garlic Butter Shrimp Pasta",
    description:
      "Succulent shrimp tossed in a rich garlic butter sauce with white wine and parmesan over linguine. Elegant enough for guests, easy enough for a weeknight.",
    imageUrl:
      "https://images.unsplash.com/photo-1677681483419-e18aa1376db7?w=800",
    cuisine: "Italian",
    cookTimeMinutes: 25,
    baseServings: 4,
    tags: ["pasta", "seafood", "italian"],
    instructions: [
      "Bring a large pot of salted water to a boil and cook linguine until al dente.",
      "Pat shrimp dry and season with salt and pepper.",
      "Melt butter in a large skillet over medium-high heat.",
      "Add shrimp and cook 1 to 2 minutes per side until pink, then set aside.",
      "Add garlic to the skillet and cook for 1 minute until fragrant.",
      "Pour in white wine and simmer for 2 minutes.",
      "Add drained pasta to the skillet and toss to coat.",
      "Return shrimp to the pan, top with parmesan and parsley, and serve.",
    ],
    ingredients: [
      { id: "5-1", name: "Linguine", quantity: 400, unit: "g" },
      { id: "5-2", name: "Shrimp", quantity: 500, unit: "g" },
      { id: "5-3", name: "Butter", quantity: 4, unit: "tbsp" },
      { id: "5-4", name: "Garlic", quantity: 5, unit: "" },
      { id: "5-5", name: "White wine", quantity: 0.5, unit: "cup" },
      { id: "5-6", name: "Parmesan", quantity: 0.5, unit: "cup" },
      { id: "5-7", name: "Fresh parsley", quantity: 0.25, unit: "cup" },
    ],
  },
];
